import { Product, Prompt, Answer } from "./types"

export const trackedProducts: Product[] = [
  { id: "all", name: "All Products", count: 169, domain: "" },
  {
    id: "product-1",
    name: "Gaiam Balance Ball Chair - No-Roll Ergonomic Office Chair & Yoga Ball Chair for Home Office Desk",
    count: 45,
    domain: "gaiam.com",
  },
  {
    id: "product-2",
    name: "Gaiam Classic Balance Ball Chair – Ergonomic Stability Chair for Desk & Office | Yoga Ball S...",
    count: 38,
    domain: "gaiam.com",
  },
  {
    id: "product-3",
    name: "Gaiam Balance Disc Wobble Cushion Stability Core Trainer for Home or Office Desk Chair &...",
    count: 42,
    domain: "gaiam.com",
  },
  { id: "product-4", name: "Gaiam Balance Ball Chair - Blue", count: 44, domain: "gaiam.com" },
]

export const mockPrompts: Prompt[] = [
  {
    id: 1,
    text: "product management platforms with agile product lifecycle management features",
    source: "chatgpt",
    personas: ["Student", "Professional"],
    position: 9.5,
    topic: "product-mgmt",
    type: "geo" as const,
    location: { country: "United States", city: "San Francisco", language: "English" },
    llms: ["ChatGPT", "Perplexity"],
    productSnippet: "Product Management Platform - Enterprise",
    product: "Gaiam Balance Ball Chair - No-Roll Ergonomic Office Chair & Yoga Ball Chair for Home Office Desk",
  },
  {
    id: 2,
    text: "What are some of the key things product teams look for in a management tool?",
    source: "google",
    personas: ["Professional"],
    position: 9,
    topic: "product-mgmt",
    type: "seo" as const,
    location: { country: "United States", city: "New York", language: "English" },
    llms: ["Google"],
    productSnippet: "",
    product: "Gaiam Balance Ball Chair - No-Roll Ergonomic Office Chair & Yoga Ball Chair for Home Office Desk",
  },
  {
    id: 3,
    text: "what is the cost of restoration project management software",
    source: "chatgpt",
    personas: ["Parent", "Outdoor"],
    position: 8.5,
    topic: "product-mgmt",
    type: "geo" as const,
    location: { country: "Canada", city: "Toronto", language: "English" },
    llms: ["ChatGPT"],
    productSnippet: "",
    product: "Gaiam Classic Balance Ball Chair – Ergonomic Stability Chair for Desk & Office | Yoga Ball S...",
  },
  {
    id: 4,
    text: "scheduling software vs dedicated product management platforms",
    source: "google",
    personas: ["Professional", "Student"],
    position: 8.2,
    topic: "product-mgmt",
    type: "seo" as const,
    location: { country: "United Kingdom", city: "London", language: "English" },
    llms: ["Google"],
    productSnippet: "",
    product: "Gaiam Balance Disc Wobble Cushion Stability Core Trainer for Home or Office Desk Chair &...",
  },
  {
    id: 5,
    text: "Research tools for product management team collaboration",
    source: "perplexity",
    personas: ["Professional"],
    position: 8.14,
    topic: "product-mgmt",
    type: "geo" as const,
    location: { country: "Australia", city: "Sydney", language: "English" },
    llms: ["Perplexity"],
    productSnippet: "",
    product: "Gaiam Balance Ball Chair - Blue",
  },
  {
    id: 6,
    text: "what project management software does health care use",
    source: "chatgpt",
    personas: ["Professional", "Parent"],
    position: 7.4,
    topic: "product-mgmt",
    type: "geo" as const,
    location: { country: "Germany", city: "Berlin", language: "German" },
    llms: ["ChatGPT"],
    productSnippet: "",
    product: "Gaiam Balance Ball Chair - No-Roll Ergonomic Office Chair & Yoga Ball Chair for Home Office Desk",
  },
  {
    id: 7,
    text: "What are the best product management tools available?",
    source: "reddit",
    personas: ["Student", "Outdoor"],
    position: 7.25,
    topic: "product-mgmt",
    type: "seo" as const,
    location: { country: "France", city: "Paris", language: "French" },
    llms: ["Reddit"],
    productSnippet: "",
    product: "Gaiam Classic Balance Ball Chair – Ergonomic Stability Chair for Desk & Office | Yoga Ball S...",
  },
  {
    id: 8,
    text: "what are the tools helpful in product launches",
    source: "google",
    personas: ["Professional"],
    position: 7.2,
    topic: "product-mgmt",
    type: "geo" as const,
    location: { country: "Japan", city: "Tokyo", language: "Japanese" },
    llms: ["Google"],
    productSnippet: "",
    product: "Gaiam Balance Ball Chair - No-Roll Ergonomic Office Chair & Yoga Ball Chair for Home Office Desk",
  },
  {
    id: 9,
    text: "best ergonomic office chairs for back pain relief",
    source: "chatgpt",
    personas: ["Professional", "Parent"],
    position: 6.8,
    topic: "ergonomics",
    type: "geo" as const,
    location: { country: "United States", city: "Los Angeles", language: "English" },
    llms: ["ChatGPT", "Gemini"],
    productSnippet: "Ergonomic Balance Ball Chair",
    product: "Gaiam Balance Ball Chair - No-Roll Ergonomic Office Chair & Yoga Ball Chair for Home Office Desk",
  },
  {
    id: 10,
    text: "how to improve posture while working from home",
    source: "perplexity",
    personas: ["Professional", "Student"],
    position: 6.5,
    topic: "ergonomics",
    type: "seo" as const,
    location: { country: "United States", city: "Chicago", language: "English" },
    llms: ["Perplexity"],
    productSnippet: "",
    product: "Gaiam Classic Balance Ball Chair – Ergonomic Stability Chair for Desk & Office | Yoga Ball S...",
  },
  {
    id: 11,
    text: "balance ball chair benefits for core strength",
    source: "gemini",
    personas: ["Outdoor", "Professional"],
    position: 6.2,
    topic: "fitness",
    type: "geo" as const,
    location: { country: "United States", city: "Austin", language: "English" },
    llms: ["Gemini"],
    productSnippet: "Balance Ball Chair for Core Training",
    product: "Gaiam Balance Ball Chair - Blue",
  },
  {
    id: 12,
    text: "active sitting solutions for office workers",
    source: "chatgpt",
    personas: ["Professional"],
    position: 5.9,
    topic: "ergonomics",
    type: "geo" as const,
    location: { country: "Canada", city: "Vancouver", language: "English" },
    llms: ["ChatGPT"],
    productSnippet: "",
    product: "Gaiam Balance Disc Wobble Cushion Stability Core Trainer for Home or Office Desk Chair &...",
  },
  {
    id: 13,
    text: "wobble cushion exercises for stability training",
    source: "perplexity",
    personas: ["Outdoor", "Student"],
    position: 5.7,
    topic: "fitness",
    type: "seo" as const,
    location: { country: "United Kingdom", city: "Manchester", language: "English" },
    llms: ["Perplexity", "Gemini"],
    productSnippet: "Stability Training Cushion",
    product: "Gaiam Balance Disc Wobble Cushion Stability Core Trainer for Home or Office Desk Chair &...",
  },
  {
    id: 14,
    text: "alternatives to traditional office chairs",
    source: "google",
    personas: ["Professional", "Parent"],
    position: 5.5,
    topic: "ergonomics",
    type: "geo" as const,
    location: { country: "Australia", city: "Melbourne", language: "English" },
    llms: ["Google"],
    productSnippet: "",
    product: "Gaiam Classic Balance Ball Chair – Ergonomic Stability Chair for Desk & Office | Yoga Ball S...",
  },
  {
    id: 15,
    text: "how to reduce lower back pain at desk job",
    source: "chatgpt",
    personas: ["Professional"],
    position: 5.3,
    topic: "health",
    type: "seo" as const,
    location: { country: "United States", city: "Seattle", language: "English" },
    llms: ["ChatGPT", "Perplexity"],
    productSnippet: "",
    product: "Gaiam Balance Ball Chair - No-Roll Ergonomic Office Chair & Yoga Ball Chair for Home Office Desk",
  },
  {
    id: 16,
    text: "balance training equipment for home office",
    source: "gemini",
    personas: ["Outdoor", "Professional"],
    position: 5.1,
    topic: "fitness",
    type: "geo" as const,
    location: { country: "Germany", city: "Munich", language: "German" },
    llms: ["Gemini"],
    productSnippet: "Home Office Balance Equipment",
    product: "Gaiam Balance Disc Wobble Cushion Stability Core Trainer for Home or Office Desk Chair &...",
  },
  {
    id: 17,
    text: "ergonomic seating options for small spaces",
    source: "perplexity",
    personas: ["Student", "Professional"],
    position: 4.9,
    topic: "ergonomics",
    type: "geo" as const,
    location: { country: "United States", city: "Boston", language: "English" },
    llms: ["Perplexity"],
    productSnippet: "",
    product: "Gaiam Classic Balance Ball Chair – Ergonomic Stability Chair for Desk & Office | Yoga Ball S...",
  },
  {
    id: 18,
    text: "stability ball chair reviews and comparisons",
    source: "reddit",
    personas: ["Professional", "Parent"],
    position: 4.7,
    topic: "reviews",
    type: "seo" as const,
    location: { country: "Canada", city: "Montreal", language: "English" },
    llms: ["Reddit"],
    productSnippet: "",
    product: "Gaiam Balance Ball Chair - No-Roll Ergonomic Office Chair & Yoga Ball Chair for Home Office Desk",
  },
  {
    id: 19,
    text: "core strengthening while sitting at desk",
    source: "chatgpt",
    personas: ["Professional", "Outdoor"],
    position: 4.5,
    topic: "fitness",
    type: "geo" as const,
    location: { country: "Spain", city: "Madrid", language: "Spanish" },
    llms: ["ChatGPT"],
    productSnippet: "Desk Core Training Solution",
    product: "Gaiam Balance Ball Chair - No-Roll Ergonomic Office Chair & Yoga Ball Chair for Home Office Desk",
  },
  {
    id: 20,
    text: "best balance cushions for office chairs",
    source: "google",
    personas: ["Professional"],
    position: 4.3,
    topic: "ergonomics",
    type: "seo" as const,
    location: { country: "Italy", city: "Rome", language: "Italian" },
    llms: ["Google"],
    productSnippet: "",
    product: "Gaiam Balance Disc Wobble Cushion Stability Core Trainer for Home or Office Desk Chair &...",
  },
  {
    id: 21,
    text: "improve focus and concentration with active sitting",
    source: "perplexity",
    personas: ["Student", "Professional"],
    position: 4.1,
    topic: "productivity",
    type: "geo" as const,
    location: { country: "Netherlands", city: "Amsterdam", language: "Dutch" },
    llms: ["Perplexity", "Gemini"],
    productSnippet: "",
    product: "Gaiam Classic Balance Ball Chair – Ergonomic Stability Chair for Desk & Office | Yoga Ball S...",
  },
  {
    id: 22,
    text: "yoga ball chair for office use",
    source: "chatgpt",
    personas: ["Professional", "Parent"],
    position: 3.9,
    topic: "ergonomics",
    type: "geo" as const,
    location: { country: "United States", city: "Denver", language: "English" },
    llms: ["ChatGPT"],
    productSnippet: "Yoga Ball Office Chair",
    product: "Gaiam Balance Ball Chair - Blue",
  },
  {
    id: 23,
    text: "prevent slouching with ergonomic seating",
    source: "gemini",
    personas: ["Professional"],
    position: 3.7,
    topic: "health",
    type: "seo" as const,
    location: { country: "Sweden", city: "Stockholm", language: "Swedish" },
    llms: ["Gemini"],
    productSnippet: "",
    product: "Gaiam Balance Ball Chair - No-Roll Ergonomic Office Chair & Yoga Ball Chair for Home Office Desk",
  },
  {
    id: 24,
    text: "balance disc exercises for beginners",
    source: "perplexity",
    personas: ["Outdoor", "Student"],
    position: 3.5,
    topic: "fitness",
    type: "geo" as const,
    location: { country: "Brazil", city: "São Paulo", language: "Portuguese" },
    llms: ["Perplexity"],
    productSnippet: "Beginner Balance Training",
    product: "Gaiam Balance Disc Wobble Cushion Stability Core Trainer for Home or Office Desk Chair &...",
  },
  {
    id: 25,
    text: "affordable ergonomic chair alternatives",
    source: "reddit",
    personas: ["Student", "Professional"],
    position: 3.3,
    topic: "budget",
    type: "seo" as const,
    location: { country: "India", city: "Mumbai", language: "English" },
    llms: ["Reddit"],
    productSnippet: "",
    product: "Gaiam Classic Balance Ball Chair – Ergonomic Stability Chair for Desk & Office | Yoga Ball S...",
  },
]

export const mockAnswers: Answer[] = [
  {
    date: "2025-01-15",
    llm: "ChatGPT",
    answer:
      "For small businesses seeking the best product management platforms, I recommend Asana, Monday.com, and Jira...",
    fullAnswer:
      "For small businesses seeking the best product management platforms, I recommend Asana, Monday.com, and Jira as top choices. Asana excels in task management and team collaboration with its intuitive interface and flexible project views. Monday.com offers excellent customization options and visual workflows that make it easy to track progress across multiple projects. Jira is particularly strong for software development teams with its robust issue tracking and agile project management features. Each platform offers different pricing tiers to accommodate growing businesses, with Asana starting at $10.99/user/month, Monday.com at $8/user/month, and Jira at $7.75/user/month. All three integrate well with popular tools like Slack, Google Drive, and Microsoft Teams, making them versatile choices for modern product teams.",
    rank: 1,
    personas: ["Small Business Owner", "Product Manager"],
  },
  {
    date: "2025-01-14",
    llm: "Perplexity",
    answer: "The top product management platforms for agile teams include Aha!, ProductPlan, and Roadmunk...",
    fullAnswer:
      "The top product management platforms for agile teams include Aha!, ProductPlan, and Roadmunk, each offering unique strengths for strategic planning and roadmapping. Aha! is a comprehensive solution that combines roadmapping, idea management, and strategic planning in one platform, making it ideal for enterprise teams that need to align product strategy with company goals. ProductPlan focuses on visual roadmapping with drag-and-drop functionality and real-time collaboration features, perfect for teams that stakeholder communication. Roadmunk specializes in creating beautiful, presentation-ready roadmaps with multiple view options including timeline, swimlane, and portfolio views. These platforms typically range from $59-$149 per user per month, with enterprise pricing available for larger organizations. They all support agile methodologies and integrate with development tools like Jira, Azure DevOps, and GitHub.",
    rank: 3,
    personas: ["Agile Team Lead", "Scrum Master"],
  },
  {
    date: "2025-01-13",
    llm: "ChatGPT",
    answer: "Based on recent reviews, the best product management tools are Productboard, Pendo, and Amplitude...",
    fullAnswer:
      "Based on recent reviews, the best product management tools are Productboard, Pendo, and Amplitude, each serving different aspects of the product lifecycle. Productboard stands out for its customer feedback aggregation and prioritization framework, helping teams make data-driven decisions about what to build next. It includes features like user research repositories, feature scoring, and roadmap sharing capabilities. Pendo combines product analytics with in-app guidance and feedback collection, making it excellent for SaaS companies looking to improve user adoption and retention. Amplitude focuses on behavioral analytics and experimentation, providing deep insights into how users interact with your product through event tracking and cohort analysis. Pricing varies significantly: Productboard starts at $20/user/month, Pendo offers custom enterprise pricing, and Amplitude has a free tier with paid plans starting at $49/month. These tools are particularly valuable for product-led growth companies.",
    rank: 2,
    personas: ["Product Manager", "Data Analyst"],
  },
]

