export const trafficData = [
  {
    date: "Sep 14",
    amazonAppearances: 245,
    amazonReferrals: 89,
    shopifyAppearances: 189,
    shopifyReferrals: 67,
    chatgptAmazon: 98,
    chatgptShopify: 76,
    geminiAmazon: 82,
    geminiShopify: 67,
    perplexityAmazon: 65,
    perplexityShopify: 50,
    // Position data (lower is better)
    chatgptAmazonPos: 3.2,
    chatgptShopifyPos: 3.8,
    geminiAmazonPos: 4.1,
    geminiShopifyPos: 4.5,
    perplexityAmazonPos: 4.8,
    perplexityShopifyPos: 5.2,
  },
  {
    date: "Sep 15",
    amazonAppearances: 268,
    amazonReferrals: 95,
    shopifyAppearances: 201,
    shopifyReferrals: 72,
    chatgptAmazon: 107,
    chatgptShopify: 81,
    geminiAmazon: 89,
    geminiShopify: 67,
    perplexityAmazon: 72,
    perplexityShopify: 53,
    chatgptAmazonPos: 3.0,
    chatgptShopifyPos: 3.6,
    geminiAmazonPos: 3.9,
    geminiShopifyPos: 4.3,
    perplexityAmazonPos: 4.6,
    perplexityShopifyPos: 5.0,
  },
  {
    date: "Sep 16",
    amazonAppearances: 289,
    amazonReferrals: 102,
    shopifyAppearances: 215,
    shopifyReferrals: 78,
    chatgptAmazon: 116,
    chatgptShopify: 86,
    geminiAmazon: 96,
    geminiShopify: 72,
    perplexityAmazon: 77,
    perplexityShopify: 57,
    chatgptAmazonPos: 2.8,
    chatgptShopifyPos: 3.4,
    geminiAmazonPos: 3.7,
    geminiShopifyPos: 4.1,
    perplexityAmazonPos: 4.4,
    perplexityShopifyPos: 4.8,
  },
  {
    date: "Sep 17",
    amazonAppearances: 312,
    amazonReferrals: 110,
    shopifyAppearances: 234,
    shopifyReferrals: 85,
    chatgptAmazon: 125,
    chatgptShopify: 94,
    geminiAmazon: 104,
    geminiShopify: 78,
    perplexityAmazon: 83,
    perplexityShopify: 62,
    chatgptAmazonPos: 2.6,
    chatgptShopifyPos: 3.2,
    geminiAmazonPos: 3.5,
    geminiShopifyPos: 3.9,
    perplexityAmazonPos: 4.2,
    perplexityShopifyPos: 4.6,
  },
  {
    date: "Sep 18",
    amazonAppearances: 298,
    amazonReferrals: 105,
    shopifyAppearances: 223,
    shopifyReferrals: 81,
    chatgptAmazon: 119,
    chatgptShopify: 89,
    geminiAmazon: 99,
    geminiShopify: 74,
    perplexityAmazon: 80,
    perplexityShopify: 60,
    chatgptAmazonPos: 2.7,
    chatgptShopifyPos: 3.3,
    geminiAmazonPos: 3.6,
    geminiShopifyPos: 4.0,
    perplexityAmazonPos: 4.3,
    perplexityShopifyPos: 4.7,
  },
  {
    date: "Sep 19",
    amazonAppearances: 325,
    amazonReferrals: 115,
    shopifyAppearances: 245,
    shopifyReferrals: 89,
    chatgptAmazon: 130,
    chatgptShopify: 98,
    geminiAmazon: 108,
    geminiShopify: 82,
    perplexityAmazon: 87,
    perplexityShopify: 65,
    chatgptAmazonPos: 2.5,
    chatgptShopifyPos: 3.1,
    geminiAmazonPos: 3.4,
    geminiShopifyPos: 3.8,
    perplexityAmazonPos: 4.1,
    perplexityShopifyPos: 4.5,
  },
  {
    date: "Sep 20",
    amazonAppearances: 342,
    amazonReferrals: 121,
    shopifyAppearances: 258,
    shopifyReferrals: 94,
    chatgptAmazon: 137,
    chatgptShopify: 103,
    geminiAmazon: 114,
    geminiShopify: 86,
    perplexityAmazon: 91,
    perplexityShopify: 69,
    chatgptAmazonPos: 2.4,
    chatgptShopifyPos: 3.0,
    geminiAmazonPos: 3.3,
    geminiShopifyPos: 3.7,
    perplexityAmazonPos: 4.0,
    perplexityShopifyPos: 4.4,
  },
]

export const competitorData = [
  { rank: 1, name: "HubSpot", visibility: 65, sentiment: 86, position: 2.7, visibilityChange: 3, sentimentChange: 2 },
  {
    rank: 2,
    name: "Salesforce",
    visibility: 62,
    sentiment: 62,
    position: 2.9,
    visibilityChange: -2,
    sentimentChange: -1,
  },
  {
    rank: 3,
    name: "Your Brand",
    visibility: 47,
    sentiment: 89,
    position: 3.6,
    visibilityChange: 3,
    sentimentChange: 5,
  },
  {
    rank: 4,
    name: "Pipedrive",
    visibility: 41,
    sentiment: 76,
    position: 3.9,
    visibilityChange: -3,
    sentimentChange: 0,
  },
  { rank: 5, name: "Zero", visibility: 28, sentiment: 88, position: 2.3, visibilityChange: 4, sentimentChange: 2 },
]

// Extended competitor data for detailed lens
export const competitorDetails = {
  HubSpot: {
    performance: {
      visibility: 65,
      position: 2.7,
      sentiment: 86,
      citations: 245,
      shareOfVoice: 28,
    },
    topQueries: [
      { query: "best CRM for small business", rank: 1, intent: "Comparison", engines: ["ChatGPT", "Gemini"] },
      { query: "CRM with email automation", rank: 2, intent: "Feature Research", engines: ["ChatGPT", "Perplexity"] },
      { query: "affordable CRM pricing", rank: 1, intent: "Purchase", engines: ["ChatGPT", "Gemini"] },
    ],
    contentThemes: ["Pricing", "Automation", "Integration", "Support", "Features"],
    citedDomains: ["hubspot.com/blog", "help.hubspot.com", "academy.hubspot.com"],
    trends: [
      { date: "Week 1", visibility: 62 },
      { date: "Week 2", visibility: 65 },
      { date: "Week 3", visibility: 67 },
      { date: "Week 4", visibility: 65 },
    ]
  },
  Salesforce: {
    performance: {
      visibility: 62,
      position: 2.9,
      sentiment: 62,
      citations: 198,
      shareOfVoice: 22,
    },
    topQueries: [
      { query: "enterprise CRM solutions", rank: 1, intent: "Purchase", engines: ["ChatGPT", "Gemini"] },
      { query: "CRM for large companies", rank: 2, intent: "Comparison", engines: ["Perplexity", "Gemini"] },
      { query: "salesforce vs competitors", rank: 3, intent: "Comparison", engines: ["ChatGPT"] },
    ],
    contentThemes: ["Enterprise", "Scalability", "Integration", "Security", "Analytics"],
    citedDomains: ["salesforce.com", "trailhead.salesforce.com", "help.salesforce.com"],
    trends: [
      { date: "Week 1", visibility: 64 },
      { date: "Week 2", visibility: 63 },
      { date: "Week 3", visibility: 62 },
      { date: "Week 4", visibility: 62 },
    ]
  },
  "Your Brand": {
    performance: {
      visibility: 47,
      position: 3.6,
      sentiment: 89,
      citations: 156,
      shareOfVoice: 18,
    },
    topQueries: [
      { query: "best CRM for small business", rank: 3, intent: "Comparison", engines: ["ChatGPT"] },
      { query: "affordable CRM software", rank: 5, intent: "Purchase", engines: ["Gemini"] },
      { query: "CRM with email integration", rank: 2, intent: "Feature Research", engines: ["Perplexity"] },
    ],
    contentThemes: ["User-friendly", "Cost-effective", "Customer Support", "Quick Setup"],
    citedDomains: ["yourbrand.com", "help.yourbrand.com", "blog.yourbrand.com"],
    trends: [
      { date: "Week 1", visibility: 44 },
      { date: "Week 2", visibility: 46 },
      { date: "Week 3", visibility: 47 },
      { date: "Week 4", visibility: 47 },
    ]
  }
}

export const queryData = [
  {
    id: 1,
    query: "best CRM for small business",
    intent: "Comparison",
    persona: "Small Business Owner",
    engines: ["ChatGPT", "Perplexity", "Gemini"],
    rank: 3,
    score: 78,
    competitors: ["HubSpot", "Salesforce"],
    whyNotRanking: "Missing pricing comparison",
  },
  {
    id: 2,
    query: "affordable CRM software",
    intent: "Purchase",
    persona: "Startup Founder",
    engines: ["ChatGPT", "Gemini"],
    rank: 5,
    score: 65,
    competitors: ["Pipedrive", "Zoho"],
    whyNotRanking: "Weak feature descriptions",
  },
  {
    id: 3,
    query: "CRM with email integration",
    intent: "Feature Research",
    persona: "Sales Manager",
    engines: ["Perplexity", "Gemini"],
    rank: 2,
    score: 85,
    competitors: ["Salesforce"],
    whyNotRanking: "Limited integration examples",
  },
]

export const platformVisibilityData = [
  { platform: "OpenAI", visibility: 48, icon: "/chatgpt-logo.svg" },
  { platform: "Google", visibility: 38, icon: "/gemini-logo.jpeg" },
  { platform: "Perplexity", visibility: 28, icon: "/perplexity-logo.png" },
]

export const rankDistributionData = [
  { rank: "1st rank", percentage: 10.8, answers: 25 },
  { rank: "2nd rank", percentage: 17.3, answers: 40 },
  { rank: "3rd rank", percentage: 22.1, answers: 51 },
  { rank: "4th rank", percentage: 15.4, answers: 36 },
  { rank: "5th rank and below", percentage: 34.4, answers: 79 },
]

export const topCitedDomainsData = [
  { domain: "reddit.com", answers: 145, icon: "🔴" },
  { domain: "zapier.com", answers: 129, icon: "🟠" },
  { domain: "wikipedia.org", answers: 125, icon: "W" },
  { domain: "atlassian.com", answers: 96, icon: "🔷" },
  { domain: "clickup.com", answers: 78, isYou: true, icon: "C" },
  { domain: "thedigitalprojectmanager.com", answers: 74, icon: "📊" },
]

export const topCitedPagesData = [
  {
    title: "We Tried 25 Free Project Management Software: Only One Nailed It",
    url: "https://clickup.com/blog/free-project-management-software/",
    answers: 24,
  },
  {
    title: "15 Best Agile Tools for Streamlined Project Management in 2025",
    url: "https://clickup.com/blog/agile-tools/",
    answers: 7,
  },
  {
    title: "15 Best Microsoft Project Alternatives for 2025 | ClickUp",
    url: "https://clickup.com/blog/microsoft-project-alternatives/",
    answers: 5,
  },
  {
    title: "Honest Review of the 15 Best Project Management Tools that I Used",
    url: "https://clickup.com/blog/best-project-management-tools/",
    answers: 4,
  },
]

export const visibilityTrendsData = [
  { date: "Jun 28", Asana: 45, Atlassian: 38, ClickUp: 36, Monday: 30, Trello: 25, Wrike: 23 },
  { date: "Jun 29", Asana: 46, Atlassian: 39, ClickUp: 37, Monday: 31, Trello: 26, Wrike: 24 },
  { date: "Jun 30", Asana: 47, Atlassian: 40, ClickUp: 38, Monday: 32, Trello: 27, Wrike: 25 },
]

export const mockProducts = [
  { id: "1", name: "Wireless Bluetooth Headphones", isTop3: true },
  { id: "2", name: "Smart Fitness Tracker", isTop3: true },
  { id: "3", name: "Portable Phone Charger", isTop3: true },
  { id: "4", name: "USB-C Hub Adapter", isTop3: false },
  { id: "5", name: "Laptop Stand", isTop3: false },
  { id: "6", name: "Wireless Mouse", isTop3: false },
  { id: "7", name: "Keyboard Cover", isTop3: false },
]
